name: Build PR
on: [pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.17]
        steps:
            - uses: actions/checkout@v1
            - name: Check cache
              id: cache
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}-0
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Use Node ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install dependencies
              run: yarn install
            - name: run linting
              run: yarn ci-lint
            - name: run tests
              run: yarn cover
            - name: Publish Unit Test Results
              uses: EnricoMi/publish-unit-test-result-action@v1
              if: always()
              with:
                  files: coverage/**/*.xml
            - name: build code
              run: yarn build
            - name: copy file branch
              run: |
                  path=upload/$CI_REF_NAME && mkdir -p ${path%"/merge"} && cp -R coverage/index.html coverage/coverage.html &&
                  cp -R coverage/coverage.html coverage/base.css coverage/prettify.css ${path%"/merge"}&& cp -R dist/* ${path%"/merge"}
            - name: publish to Azure
              uses: lauchacarro/Azure-Storage-Action@v1.1
              with:
                  # Connection String of the Azure Storage Container
                  connection-string: ${{ secrets.AZURE_CDN_SECRET }}
                  # Folder what contains the files for upload to Storage Container
                  folder: upload
                  # Name of Blob Container Storage
                  blob-container-name: workspace
                  public-access-policy: BlobContainer