name: Build PR
on: [pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.17]
        steps:
            - uses: actions/checkout@v1
            - name: Check cache
              id: cache
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}-0
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Use Node ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install dependencies
              run: yarn install
            - name: run linting
              run: yarn ci-lint
            - name: run tests
              run: yarn cover
            - name: Publish Unit Test Results
              uses: EnricoMi/publish-unit-test-result-action@v1
              if: always()
              with:
                  files: coverage/**/*.xml
            - name: build code
              run: yarn build
